### ISSUE TITLE
How to configure JANUS freshly installed with APT on Ubuntu to successfully connect with Laravel-RT/Messenger-Demo ???

### ISSUE THREAD

**Issue by chegmarco1989** [RTippin/janus-client#4]
Hello.

**I really need help that's why I'm making posts because the moses in place of _Laravel-RT/Messenger-Demo_ (https://github.com/RTippin/messenger-demo) isn't easy.** I am now at the level of the installation of the **Janus Server** which causes me a lot of problems. I had already installed Janus by following the instructions in this link: [https://facsiaginsa.com/janus/install-janus-webrtc-server-on-ubuntu](https://facsiaginsa.com/janus/install-janus-webrtc-server-on-ubuntu). The installation was successful. But slowly, the Janus Server does not start anymore. So I finally deleted what I had installed and tried a new way to install **Janus** via the command: `sudo apt-get install janus -y`.
So after the installation via `APT`, I would like to ask a few questions related to getting **Janus** started properly:

1 - Must I also and necessarily install the `Stun` and `Turn` Servers before configuring the Janus Server that I have just installed and before finally configuring with **Laravel-RT/Messenger-Demo** ???

2 - Please, how to configure **Janus** on _Ubuntu_ step by step to successfully connect with **Laravel-RT/Messenger-Demo** ???

Please enlighten me and/or guide me.

**Comment by ajnozari** [comment]
You really need to read the Janus documentation.  This repo is a wrapper for Janus to be controlled and interfaced with through laravel.  It relies on YOU to configure the server and that is beyond the scope of this repo.

However, to answer your question I’d recommend you not install Janus directly on Ubuntu but instead use this:

[https://github.com/atyenoria/janus-webrtc-gateway-docker](https://github.com/atyenoria/janus-webrtc-gateway-docker) 

it’s a docker image that should simplify your life especially when setting the server up, as edits can be made and the docker image just redeployed.  

As for the stun/turn server you need to answer that yourself.  The correct question is “will my users have to traverse a NAT”.  Short answer: for most public sites it will be yes.  

If you look in the dockerfile you till see how to enable the stun and turn parts of the image, and you still have to provide config files for the server yourself.  To figure these out please refer to the Janus documentation.

**Comment by chegmarco1989** [comment]
Thank you @ajnozari for your reply.

But personally, I'm a bit confused on two levels.

**I -** Already, when I read the README of the Docker that you advise me, I do not understand **point 4** of the installation instructions:

```
1. git clone https://github.com/atyenoria/janus-webrtc-gateway-docker.git && cd janus-webrtc-gateway-docker
2. make build
3. make run
4. star this repository after succeeding. Create the issue if you failed. We will help you as much as possible
```

**How then to start the repository as advised in point 4 above ??? If not, with which command to start it and how ???**



**II -** When I open the Dockfile, I see COTURN Server installation commands:

```
RUN COTURN="4.5.0.8" && wget https://github.com/coturn/coturn/archive/$COTURN.tar.gz && \
    tar xzvf $COTURN.tar.gz && \
    cd coturn-$COTURN && \
    ./configure && \
    make && make install
```

**So, I would like to know if I have to run these Turn installation commands myself after installing the Docker image ???**

**Or by installing the Docker image itself (https://github.com/atyenoria/janus-webrtc-gateway-docker), **COTURN Server** will install automatically ???**

Please enlighten me on these two points.

**Comment by ajnozari** [comment]
@chegmarco1989 Im going to be honest it sounds like you’re not a developer, or if you are you’re just starting out.  You should spend time becoming familiar with the tools you will need to use before trying to implement things blindly.  

The 4th step is not start repo, it’s STAR the repo, as in favorite it so you can find it again.

(https://docs.github.com/en/get-started/exploring-projects-on-github/saving-repositories-with-stars)

Further what you’re asking for help with us a bit too far.  The Janus team has extensive documentation, and they clearly describe each setting and how to set them.  

The docker image is only there to make sure everything is installed right, to rule out dependency issues.  You must still mount a config to the docker image.  That’s going to require questions about your network I’m not comfortable asking over a GitHub issue.
