### ISSUE TITLE
enableRecording

### ISSUE THREAD

**Issue by abylq** [RTippin/janus-client#5]
RTippin\Janus\Exceptions\JanusPluginException: Janus Plugin Error | janus.plugin.videoroom | {"payload":{"transaction":"iLuzKOfXK68I","apis

I have problem with enableRecording how fix this 
$record = Janus::videoRoom()->enableRecording(roomID, true, 'secret');

**Comment by RTippin** [comment]
Can you please check your actual `laravel.log` error log? There may be more details about the stack trace in there. Otherwise it could be a direct Janus issue, and I would need you to inform me of what janus is telling you.

**Comment by abylq** [comment]
I add parameter pin in method enableRecording after that successfully worked

**Comment by abylq** [comment]
I send pull request please check

**Comment by RTippin** [comment]
Merged with PR https://github.com/RTippin/janus-client/pull/6

Thanks for your contribution 🙂
