### ISSUE TITLE
I used enablerecording

### ISSUE THREAD

**Issue by abylq** [RTippin/janus-client#7]
When I enable recording where I can get path to file ?

**Comment by RTippin** [comment]
Closing this issue as it does not pertain to my package. I only provide a wrapper to make the core HTTP calls to a janus server. All of the configurations for recording etc, are handled with janus's own configs. Perhaps check out:
> https://janus.conf.meetecho.com/docs/recordings.html
> https://janus.conf.meetecho.com/docs/structjanus__recorder.html
