### ISSUE TITLE
how to set .env

### ISSUE THREAD

**Issue by akofaraji** [RTippin/janus-client#8]
I want to use this package in RTippin. In the values database settings section
'server_endpoint' => env('JANUS_SERVER_ENDPOINT'),
'admin_server_endpoint' => env('JANUS_ADMIN_SERVER_ENDPOINT'),
'verify_ssl' => env('JANUS_VERIFY_SSL', true),
'debug' => env('JANUS_DEBUG', false),
'admin_secret' => env('JANUS_ADMIN_SECRET'),
'api_secret' => env('JANUS_API_SECRET'),
'video_room_secret' => env('JANUS_VIDEO_ROOM_SECRET'),
Where should it be received?
On the Janos source site, it has not mentioned about API access

**Comment by RTippin** [comment]
My janus-client is a basic wrapper that makes it secure to lockout video room creations via client side (websockets)
as janus also has an HTTP transport. Please see the following:

https://janus.conf.meetecho.com/docs/rest.html
https://janus.conf.meetecho.com/docs/auth.html

Then for example, you can set an admin key in your videoroom plugin config so only a request with the secret key can maker rooms.

https://janus.conf.meetecho.com/docs/videoroom.html
